name: Update package version

on: issue_comment

jobs:
  resolve_pr_refs:
    # This job only runs for pull request comments
    name: Resolve PR branches
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    outputs:
      target_branch: ${{ steps.refs.outputs.base_ref }}
      source_branch: ${{ steps.refs.outputs.head_ref }}
    steps:
      - uses: eficode/resolve-pr-refs@main
        id: refs
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  is_update_needed:
    name: Check whether package version update needed
    needs: resolve_pr_refs
    if: |
      ${{ needs.resolve_pr_refs.outputs.target_branch == 'main' || 'master' &&
      [[ ${{ github.event.comment.body }} == update* ]] }}
    runs-on: ubuntu-latest
    outputs:
      is_member: ${{ steps.is_organization_member.outputs.result }}
    steps:
      - name: some output
        run: |
          if  ${{ needs.resolve_pr_refs.outputs.target_branch == 'main' || 'master' }} &&
          [[ ${{ github.event.comment.body }} == update* ]] ;
          then
              echo yes1
          fi

#  is_organization_member:
#    name: Check whether user is th2 member
#    runs-on: ubuntu-latest
#    steps:

#  update_package_version:
#    name: Update package version
#    runs-on: ubuntu-latest
#    steps:

#  push_on_github:
#    name: Commit and push on github
#    runs-on: ubuntu-latest
#    steps:

#  comment_reply:
#    name: Reply to a user's comment
#    runs-on: ubuntu-latest
#    steps:
