name: Update package version

on:
  issue_comment:
    types: [created]

jobs:
  package_version_update:
    # This job only runs for pull request comments
    name: Package version update
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if organization member
        id: is_organization_member
        uses: jamessingleton/is-organization-member@main
        with:
          organization: th2-net
          username: ${{ github.event.issue.user.login }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Is member?
        run: |
          result=${{ steps.is_organization_member.outputs.result }}
          if [ $result == false ]; then
              user=${{ github.event.comment.user.login }}
              echo Either ${user} is not part of the th2-net organization
              echo or ${user} has its Organization Visibility set to Private at
              echo https://github.com/orgs/th2-net/people?query=${user}
              echo
              echo Ensure you change your Organization Visibility to Public and
              echo trigger the test again.
              exit 1
          fi
          if [ $result == true ]; then
              user=${{ github.event.comment.user.login }}
              echo ${user} is part of the th2-net organization
          fi

      - uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Get package version
        id: pack_ver
        run: |
          echo '::set-output name=package_version::$(poetry version -s)'
          echo Current package version is $(poetry version -s)

      - name: Update version
        id: update_version
        run: |
          event_body=${{ github.event.comment.body }}
          echo Event body: $event_body
          shopt -s nocasematch
          case $event_body in
          "update major") poetry version major && New package version is $(poetry version -s);;
          "update minor") poetry version minor && New package version is $(poetry version -s);;
          "update patch") poetry version patch && New package version is $(poetry version -s);;
          *) echo Update was not requested && exit 0;;
          esac

      - name: Create Comment
        run: echo Package version raised from $steps.pack_ver.outputs.package_version to $(poetry version -s) successfully.