name: Update package version

on: issue_comment

jobs:
  resolve_pr_refs:
    # This job only runs for pull request comments
    name: Resolve PR branches
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    outputs:
      target_branch: ${{ steps.refs.outputs.base_ref }}
      source_branch: ${{ steps.refs.outputs.head_ref }}
    steps:
      - uses: eficode/resolve-pr-refs@main
        id: refs
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  is_update_needed:
    name: Is package version update needed
    needs: resolve_pr_refs
    if: |
      ${{ needs.resolve_pr_refs.outputs.target_branch == 'master' || 'main' &&
      contains(github.event.comment.body, 'update') }}
    runs-on: ubuntu-latest
    steps:
      - name: Version update requested
        run: |
          echo Target branch: $needs.resolve_pr_refs.outputs.target_branch
          echo Version update requested

  is_organization_member:
    name: TH2 membership check
    needs: is_update_needed
    runs-on: ubuntu-latest
    outputs:
      is_member: ${{ steps.membership_check.outputs.result }}
    steps:
      - name: Membership check
        id: membership_check
        uses: jamessingleton/is-organization-member@main
        with:
          organization: th2-net
          username: ${{ github.event.issue.user.login }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Is member?
        run: |
          result=${{ steps.is_organization_member.outputs.result }}
          if [ $result == false ]; then
              user=${{ github.event.comment.user.login }}
              echo Either ${user} is not part of the th2-net organization
              echo or ${user} has its Organization Visibility set to Private at
              echo https://github.com/orgs/th2-net/people?query=${user}
              echo
              echo Ensure you change your Organization Visibility to Public and
              echo trigger the test again.
              exit 1
          fi
          if [ $result == true ]; then
              user=${{ github.event.comment.user.login }}
              echo '::set-output name=user_login::$user'
              echo ${user} is part of the th2-net organization
          fi

#  update_package_version:
#    name: Update package version
#    runs-on: ubuntu-latest
#    steps:

#  push_on_github:
#    name: Commit and push on github
#    runs-on: ubuntu-latest
#    steps:

#  comment_reply:
#    name: Reply to a user's comment
#    runs-on: ubuntu-latest
#    steps:
